# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-23 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(default='male', max_length=6, verbose_name='Sex'),
        ),
    ]
